site_name: 2024 年 Python 秋冬学习资料
theme: 
  name: material
  custom_dir: overrides
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - 主页: index.md
  - 常见问题: 
    - faq/index.md
    - 程序安装及使用的问题: faq/installation.md
  - 实验文档:
    - bonus/index.md
    - 环境配置指南: bonus/00env.md
    - 基于 NumPy 与 Pillow 的图像创建与基本变换: bonus/01numpy.md
  - 一些有意思的补充资料: 
    - interesting-addendum/index.md
    # - Python 虚拟环境管理: interesting-addendum/environment.md
    # - 运用 Python 学习大学数学: interesting-addendum/sympy.md